# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Shanno's Blog and Project Site
subtitle: Shanno's Blog & Open Project 
description: Shanno's Open Project include Ceph, Storage and Technology Blog Articles.
author: Xiangwei wu
language: [zh,en]
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.shanno.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: [p/**/api/*.html,p/**/api/**]

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  个人日志: personal
  惊声尖叫: scream
  残梦琐言: dream
  行云流水: essay
  转载分享: share
  软件技术: tech
  Eclipse 插件: pde
  奇淫巧技: trick
  其它: other
tag_map:
  

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
archive_generator:
  per_page: 20

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: nova

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: https://github.com/wuxiangwei/wuxiangwei.github.io.git,master
    # coding: git@git.coding.net:Jamling/Jamling,coding-pages
    # github: git@github.com:Jamling/jamling.github.com.git,master
  
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  
github:
  debug: false
  user: Jamling
  cache_dir: gh_cache
  repos:
    - Android-ORM
    - QuickAF
    - adt-extensions
    - eclipse-explorer
    - hexo-theme-nova
    - hexo-generator-i18n
i18n:
  type: [page,post]
  generator: [archive, category, tag, index]
index_generator:
#  include: category 软件技术
  
# hexo-filter-plugin (https://github.com/Jamling/hexo-filter-highlight) config 
## highlight in frontend, the plugin (backend) just do some prepare work.
## you need to read the docs on https://github.com/Jamling/hexo-filter-highlight to getting start
hljs:
  enable: true #true to enable the plugin
  line_number: frontend # add line_number in frontend or backend
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code
 
node_sass:
  outputStyle: compressed

addlink:
  before_text: <blockquote class="addlink">本文永久链接： # text before the post link
  after_text:  未经允许，禁止转载，如有问题，请在我的博客原始页面提交评论。</blockquote> # text after the post link  
